### ISSUE TITLE
T9: Fetch Categories

### ISSUE THREAD

**Issue by eceykilic** [eceykilic/ecommerce#20]
- [x] Fetch categories by **thunk action** and store it in the **gobal reducer**
- [x] endpoint “/categories“
- [x] list categories on the screen
- [x] categories should be link
- [x] on click it should navigate to “/shopping/:gender/:category”
- [x] top 5 categories should be listed on the screen with images regarding “rating” value
- [x] all categories should be listed in drop down menu on header

**Comment by eceykilic** [comment]
@gokhanozdemir @erhanfirat

**Comment by gokhanozdemir** [comment]
@eceykilic Beni projeye collab ekleyip, sonra pr açarken reviewer eklersen daha rahat yorum yapabilirim. Sonrasında review atınca, ilerlemen için merge etmen gerekiyorsa, ve ille de ben veya @erhanfirat danışarak ilerlemeniz gereken sert bir değişiklik, onay vs şey yoksa kendin, onay beklemeden, merge edip, kodun güncel halini yaniden branch açıp, oradan ilerlemeye devam edebilirsin.

**Comment by gokhanozdemir** [comment]
@eceykilic Beni projeye collab ekleyip, sonra pr açarken reviewer eklersen daha rahat yorum yapabilirim. Sonrasında review atınca, ilerlemen için merge etmen gerekiyorsa, ve ille de ben veya @erhanfirat danışarak ilerlemeniz gereken sert bir değişiklik, onay vs şey yoksa kendin, onay beklemeden, merge edip, kodun güncel halini yaniden branch açıp, oradan ilerlemeye devam edebilirsin.

**Comment by eceykilic** [comment]
@gokhanozdemir tabiki haklısınız hocam size collab isteği yolladım sonraki issuelarımda dediğiniz gibi sizi ekleyeceğim teşekkür ederim
