### ISSUE TITLE
T10: Fetch Products

### ISSUE THREAD

**Issue by eceykilic** [eceykilic/ecommerce#22]
- [x] **Fetch products**
    - [x] by **thunk action** and save it in the **product reducer**
    - [x] endpoint “/products“
    - [x] query parameters:
        - [x] category? : optional. you can limit products by sending category id
        - [x] filter?: optional. products can be filtered by the text
        - [x] sort?: optional. products can be sorted by the fields “price:asc”, “price:desc” , “rating:asc”, “rating:desc”
- [ ] you should list products in the UI (shopping page)
- [ ] while fetching products data, a loading spinner should be shown on the screen
- [x] in response you will get Object like below:
   ```js{
      total: 185,
      products: [
         { ProductObject1 }, 
         { ProductObject2 }, 
         …
      ]
   }
   ```

**Comment by gokhanozdemir** [comment]
@eceykilic beni veya Erhan Hocanızı [at]erhanfirat **assignee** değil, Pull request atarken **Reviewer** eklesen daha doğru olur. Assign ettiğin kişi, görevi yapması gereken kişi, reviewer gözden geçirip bakacak kişi demek.

**Comment by gokhanozdemir** [comment]
Yukarıdaki check listte eksikler görünüyor. Orayı da işler tamamsa işaretler misin?

**Comment by eceykilic** [comment]
@gokhanozdemir hocam optional yazan kısımlardan sadece 1 tanesini yapmam yeterli mi?

**Comment by gokhanozdemir** [comment]
O parametre request atmak için opsiyon anlamında. Opsiyonel fonksiyon parametresi gibi. Senin sistem o gereksinimleri karşılamak zorunda.
