### ISSUE TITLE
T4: Make Responsive

### ISSUE THREAD

**Issue by eceykilic** [eceykilic/ecommerce#4]
In figma design there are also mobile views. **Mobile views** should be implemented to all pages:

- [x] Home
    - [x] Shopping
    - [x] Product
    - [x] About
    - [x] Team
    - [x] Contac
- [x] [**CHECK Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)
- [x] [**CHECK Tailwind switch breakpoints min to max responsive solution:**](https://tailwindcss.com/docs/screens#max-width-breakpoints)

**Comment by eceykilic** [comment]
@gokhanozdemir

**Comment by gokhanozdemir** [comment]
Neden yeniden açtın? :)

**Comment by eceykilic** [comment]
Responsive yapıda üst kısımdaki kategorilerde yanlışlık var gibi duruyor revize etmek için tekrar açtım

**Comment by eceykilic** [comment]
@erhanfirat
